gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Build settings
kramdown:
    input: GFM
    coderay_line_numbers: nil
    hard_wrap: false

#Site content configuration
javadoc_url: /javadoc_3.x/
javers_current_version: "3.3.4"

javers_java7_version: "2.9.2"

url: "https://javers.org"

description: With JaVers you can forget about troublesome data versioning. Let the changes in your data be managed by JaVers.

permalink: /blog/:year/:month/:title.html

