gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Build settings
kramdown:
    input: GFM
    coderay_line_numbers: nil
    hard_wrap: false

#Site content configuration
javadoc_url: /javadoc_2.0/
javers_current_version: "2.8.0"

url: "http://javers.org"

